---

- name: systemd-networkd | initramfs package
  tags:
    - package
  package:
    name: initramfs-tools
  when: ansible_virtualization_type != 'openvz' 

- name: systemd-networkd | disable stable interface names
  tags:
    - network
  copy:
    content: ""
    dest: /etc/systemd/network/99-default.link
  notify: 
    - update initramfs
    - restart networkd

- name: systemd-networkd | service
  tags:
    - network
    - service
  service:
    name: systemd-networkd
    state: started
    enabled: yes
