---

- name: systemd-networkd | load handlers
  import_role:
    name: common
    tasks_from: empty.yml
    handlers_from: initramfs.yml

- name: systemd-networkd | disable stable interface names
  tags:
  - network
  copy:
    content: ""
    dest: /etc/systemd/network/99-default.link
  when: networkd_eth0_naming
  notify: 
  - update initramfs
  - reload networkd

- name: systemd-networkd | custom config
  tags:
  - config
  copy:
    content: "{{ item.value }}"
    dest: /etc/systemd/network/{{ item.key }}
  notify:
  - reload networkd
  loop: "{{ networkd_extra | dict2items }}"

- name: systemd-networkd | disable networking service
  tags:
  - network
  - service
  service:
    name: networking
    enabled: no
  when: ifup_disable

- name: systemd-networkd | service
  tags:
  - network
  - service
  service:
    name: systemd-networkd
    state: started
    enabled: yes
