---

- name: systemd-networkd | initramfs package
  tags:
  - package
  package:
    name: initramfs-tools
  when: ansible_virtualization_type != 'openvz' 

- name: systemd-networkd | disable stable interface names
  tags:
  - network
  copy:
    content: ""
    dest: /etc/systemd/network/99-default.link
  notify: 
  - update initramfs
  - daemon-reload
  - restart networkd

- name: systemd-networkd | custom templates
  tags:
  - config
  template:
    src: "{{ item.src }}"
    dest: "/etc/systemd/network/{{ item.dest }}"
  notify:
  - daemon-reload
  - restart networkd
  loop: "{{ networkd_templates }}"

- name: systemd-networkd | service
  tags:
  - network
  - service
  service:
    name: systemd-networkd
    state: started
    enabled: yes
