---

- name: systemd-networkd | disable stable interface names
  tags:
  - network
  copy:
    content: ""
    dest: /etc/systemd/network/99-default.link
  notify: 
  - update initramfs
  - daemon-reload
  - restart networkd

- name: systemd-networkd | custom config
  tags:
  - config
  copy:
    content: "{{ item.value }}"
    dest: /etc/systemd/network/{{ item.key }}
  notify:
  - daemon-reload
  - restart networkd
  loop: "{{ networkd_extra | dict2items }}"

- name: systemd-networkd | networking (ifup) service
  tags:
  - network
  - service
  service:
    name: networking
    enabled: yes

- name: systemd-networkd | service
  tags:
  - network
  - service
  service:
    name: systemd-networkd
    state: started
    enabled: yes
