#! /usr/bin/env ansible-playbook
# Configure template role
# Replace 'all' with your own inventory group
---
- name: systemd-networkd | apply role
  hosts: linux
  roles:
  - role: systemd-networkd
    tags:
    - systemd-networkd
